version: '3'
services:
  mqtt_broker:
    image: eclipse-mosquitto:latest
    ports:
    - 1883:1883
    - 9001:9001
    networks:
      freya:
        ipv4_address: 192.168.168.3
  core:
    image: hello-world:latest
    ports:
    - 6672:6672
    networks:
      freya:
        ipv4_address: 192.168.168.2
  dashboard:
    image: hello-world:latest
    ports:
    - 6673:6673
    networks:
      freya:
        ipv4_address: 192.168.168.4
networks:
  freya:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.168.0/24
