name: Python Tests

on:
    push:
        branches:
            - main  # Trigger on pushes to the main branch
            - dev
    pull_request:
        branches:
            - main  # Trigger on pull requests to the main branch

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Check out the code
            - name: Checkout code
              uses: actions/checkout@v3
    
            # Step 2: Set up uv
            - name: Install uv
              uses: astral-sh/setup-uv@v4
    
            # Step 3: Install python
            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                python-version-file: "pyproject.toml"
    
            # Step 4: Install the project
            - name: Install the project
              run: uv sync --all-extras --dev

            # Step 5: Run the tests
            - name: Run tests
              run: |
                uv run ./tests/composer.test.py
                uv run ./tests/package_manager.test.py
            
